name: JoinRestrict
version: Dev-1.4.8
main: org.aoichaan0513.joinrestrict.Main
description: JoinRestrict Plugin.
author: Aoichaan0513

commands:
  jr:
    description: JoinRestrict Main Command.
    usage: /jr ...